#!/usr/bin/env bash
# scripts/bw-env.sh — Pull workspace secrets from Bitwarden into .env
#
# Convention: store each secret as a Bitwarden Login item named:
#   autonomous-workspace/KEY_NAME
# with the secret value in the Password field.
#
# Usage:
#   bash scripts/bw-env.sh              # interactive (prompts for master password if locked)
#   bash scripts/bw-env.sh --check      # verify bw is installed and reachable, no write
#   bash scripts/bw-env.sh --list       # list available keys without writing .env
#
# Non-interactive (nightly runs): set these env vars before calling:
#   BW_CLIENTID, BW_CLIENTSECRET  — from bw.bitwarden.com → Account Settings → API Key
#   BW_PASSWORD                    — your vault master password
#
# The script exports BW_SESSION so child processes can reuse the unlocked vault.

set -euo pipefail

VAULT_PREFIX="autonomous-workspace"
ENV_FILE="${BW_ENV_FILE:-.env}"
MODE="${1:-}"

# ── helpers ──────────────────────────────────────────────────────────────────

log()  { echo "bw-env: $*"; }
warn() { echo "bw-env: WARNING: $*" >&2; }
die()  { echo "bw-env: ERROR: $*" >&2; exit 1; }

require_bw() {
  command -v bw &>/dev/null || die "Bitwarden CLI not found. Install: npm i -g @bitwarden/cli"
  command -v jq &>/dev/null || die "jq not found. Install: https://jqlang.github.io/jq/"
}

# ── auth ─────────────────────────────────────────────────────────────────────

ensure_session() {
  # Already have a valid session token in environment
  if [ -n "${BW_SESSION:-}" ]; then
    bw status --session "$BW_SESSION" 2>/dev/null | grep -q '"status":"unlocked"' && return 0
  fi

  # Non-interactive: API key login + password unlock
  if [ -n "${BW_CLIENTID:-}" ] && [ -n "${BW_CLIENTSECRET:-}" ] && [ -n "${BW_PASSWORD:-}" ]; then
    log "Logging in with API key..."
    bw login --apikey --quiet 2>/dev/null || true   # no-op if already logged in
    BW_SESSION=$(bw unlock --passwordenv BW_PASSWORD --raw 2>/dev/null)
    export BW_SESSION
    return 0
  fi

  # Interactive: prompt for master password
  STATUS=$(bw status 2>/dev/null | jq -r '.status' 2>/dev/null || echo "unauthenticated")
  if [ "$STATUS" = "unauthenticated" ]; then
    log "Not logged in. Running: bw login"
    bw login
  fi
  log "Unlocking vault..."
  BW_SESSION=$(bw unlock --raw)
  export BW_SESSION
}

# ── sync ─────────────────────────────────────────────────────────────────────

sync_vault() {
  bw sync --session "$BW_SESSION" 2>/dev/null | tail -1 || true
}

# ── fetch items ──────────────────────────────────────────────────────────────

fetch_items() {
  bw list items --search "${VAULT_PREFIX}/" --session "$BW_SESSION" 2>/dev/null \
    | jq -c --arg p "${VAULT_PREFIX}/" '[.[] | select(.name | startswith($p))]'
}

# ── modes ─────────────────────────────────────────────────────────────────────

cmd_check() {
  require_bw
  log "bw $(bw --version) — jq $(jq --version)"
  STATUS=$(bw status 2>/dev/null | jq -r '.status' 2>/dev/null || echo "unknown")
  log "Vault status: $STATUS"
  log "OK"
}

cmd_list() {
  require_bw
  ensure_session
  sync_vault
  ITEMS=$(fetch_items)
  COUNT=$(echo "$ITEMS" | jq 'length')
  if [ "$COUNT" -eq 0 ]; then
    log "No items found with prefix '${VAULT_PREFIX}/'"
    log "Create one: task secrets:set -- KEY_NAME value"
    return 0
  fi
  log "Found $COUNT secret(s):"
  echo "$ITEMS" | jq -r --arg p "${VAULT_PREFIX}/" '.[] | "  " + .name[($p|length):]'
}

cmd_pull() {
  require_bw
  ensure_session
  sync_vault

  ITEMS=$(fetch_items)
  COUNT=$(echo "$ITEMS" | jq 'length')

  if [ "$COUNT" -eq 0 ]; then
    warn "No items found with prefix '${VAULT_PREFIX}/'. Leaving $ENV_FILE unchanged."
    log "Add secrets with: task secrets:set -- KEY_NAME value"
    return 0
  fi

  # Write .env
  {
    echo "# Auto-generated by scripts/bw-env.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Source: Bitwarden prefix '${VAULT_PREFIX}/'"
    echo "# Do not edit manually. Regenerate with: task secrets:pull"
    echo ""
    echo "$ITEMS" | jq -r --arg p "${VAULT_PREFIX}/" \
      '.[] | (.name[($p|length):]) + "=" + (.login.password // .notes // "")'
  } > "$ENV_FILE"

  log "Wrote $COUNT secret(s) to $ENV_FILE"
}

# ── dispatch ──────────────────────────────────────────────────────────────────

case "$MODE" in
  --check) cmd_check ;;
  --list)  cmd_list  ;;
  *)       cmd_pull  ;;
esac
